### ASSIGNMENT_4 ###
Cognitive Computing
Ritesh_Patel: 102367004

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic 
operations like: 
a) Addition of 2 in all the element  
b) Multiply 3 with all the elements 
c) Divide every element by 2 

In [33]:
import numpy as np

arr=np.array([10,20,30,40,50])

add_result=arr+2
print(add_result)
mul_result=arr*3
print(mul_result)
div_result=arr/2
print(div_result)
print("Original Arrray",arr)



[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]
Original Arrray [10 20 30 40 50]


Q.2 Questions on Basic NumPy Array: 
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 
b) Find the most frequent value and their indice(s) in the following arrays: 
i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [36]:
import numpy as np

arr=np.array([1,2,3,4,5])

rev_array=arr[::-1]

print("Original array",arr)

print("Reverse Array",rev_array)




Original array [1 2 3 4 5]
Reverse Array [5 4 3 2 1]


In [1]:
import numpy as np
from collections import Counter

def most_frequent_values(arr):
    counts = Counter(arr)
    max_freq = max(counts.values())
    most_frequent = [key for key, val in counts.items() if val == max_freq]
    indices = {val: np.where(arr == val)[0].tolist() for val in most_frequent}
    return most_frequent, indices

# Define the arrays
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

# Find the most frequent values and their indices
most_frequent_x, indices_x = most_frequent_values(x)
most_frequent_y, indices_y = most_frequent_values(y)

print(f"Most frequent value(s) in x: {most_frequent_x}, Indices: {indices_x}")
print(f"Most frequent value(s) in y: {most_frequent_y}, Indices: {indices_y}")



Most frequent value(s) in x: [1], Indices: {1: [0, 5, 7, 8, 9]}
Most frequent value(s) in y: [1, 3], Indices: {1: [0, 1, 2], 3: [4, 8, 9]}


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access 
elements using row and column indices as follows: 
a) Access 1st row, 2nd column  
b) Access 3rd row, 1st column

In [41]:
import numpy as np
arr=np.array([[10,20,30],
             [40,50,60],
             [70,80,90]])
#a_part 1st row 2nd column
element_a=arr[0,1]
print(element_a)
#b_part 3rd row 1st column
element_b=arr[2,0]
print(element_b)


20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly 
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, 
shape, total elements, the data type of each element and total number of bytes consumed 
by the array. Find the transpose of this array using reshape() attribute. Can we do the same 
with T attribute?

In [57]:
import numpy as np
Ritesh_Patel=np.linspace(10,100,25)
print("Array: ",Ritesh_Patel)
print(Ritesh_Patel.ndim)
print(Ritesh_Patel.shape)
print(Ritesh_Patel.size)
print(Ritesh_Patel.dtype)
print(Ritesh_Patel.nbytes)

#transposed Array
transpose_array=Ritesh_Patel.reshape(25,1)
print("Transpose:",transpose_array)

#transpose using T
transpose_T=Ritesh_Patel.T
print(transpose_T)
#shape after using T 
print(transpose_T.shape)


Array:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
Transpose: [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25,)


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> 
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, 
median, max, min, unique elements. Reshape the array to four rows and three columns and 
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three 
columns and name it as resized_ ucs420_<your_name>>.

In [3]:
import numpy as np
 
ucs420_Ritesh = np.array([[10, 20, 30, 40], 
                          [50, 60, 70, 80], 
                          [90, 15, 20, 35]])
 
mean_value = np.mean(ucs420_Ritesh)
median_value = np.median(ucs420_Ritesh)
max_value = np.max(ucs420_Ritesh)
min_value = np.min(ucs420_Ritesh)
unique_elements = np.unique(ucs420_Ritesh)
 
print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)
 
reshaped_ucs420_Ritesh = ucs420_Ritesh.reshape(4, 3)
print("Reshaped Array (4x3):\n", reshaped_ucs420_Ritesh)
 
resized_ucs420_Ritesh = ucs420_Ritesh.copy()
resized_ucs420_Ritesh.resize(2, 3)
print("Resized Array (2x3):\n", resized_ucs420_Ritesh)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
